import os
import json
import numpy as np
from typing import Any, Tuple
import soundfile as sf
import torch
from pytorch_lightning import LightningDataModule
# from pytorch_lightning.core.mixins import HyperparametersMixin
from torch.utils.data import ConcatDataset, DataLoader, Dataset
from typing import Dict, Iterable, List, Iterator
from rich import print
from pytorch_lightning.utilities import rank_zero_only
import json
from pathlib import Path
from typing import List, Optional, Tuple
from bisect import bisect_right

import numpy as np
import soundfile as sf
import torch
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

import re


@rank_zero_only
def print_(message: str):
    print(message)


def normalize_tensor_wav(wav_tensor, eps=1e-8, std=None):
    mean = wav_tensor.mean(-1, keepdim=True)
    if std is None:
        std = wav_tensor.std(-1, keepdim=True)
    return (wav_tensor - mean) / (std + eps)


"ECHIDataset(Dataset)"


def session_key_from_path(path: str) -> str:
    m = re.search(r"\b(train|dev|eval)_\d+\b", Path(path).name)
    if not m:
        raise ValueError(f"Could not extract session key from: {path}")
    return m.group(0)


class ECHIDataset(Dataset):
    """
    Hybrid long-recording dataset:
    - reads manifests generated by preprocess_echi.py
    - builds a global segment index (prefix sums)
    - __getitem__ returns (mixture[T], targets[n_src,T], utt_id) as expected by look2hear.system
      :contentReference[oaicite:6]{index=6}
    """

    def __init__(
        self,
        json_dir: str | Path,         # .../Processed_ECHI/<device>/<split>/
        n_src: int = 4,               # pos1..pos4
        sample_rate: int = 16000,
        segment: float = 3.0,         # seconds
        hop: Optional[float] = None,  # seconds; default = segment (no overlap)
        pad_last: bool = False,       # set True for val/test if you want full coverage
        dtype: str = "float32",
        return_path: bool = True,     # third element: path (as in MP3DDataset) vs session key
        mixture_mode: str = "manifest",  # "manifest" (default) or "target_sum"
    ) -> None:
        super().__init__()
        self.json_dir = Path(json_dir)
        self.n_src = n_src
        self.sr = int(sample_rate)
        self.seg_len = int(round(segment * self.sr))
        self.hop_len = int(round((hop if hop is not None else segment) * self.sr))
        self.pad_last = pad_last
        self.dtype = dtype
        self.return_path = return_path
        self.mixture_mode = str(mixture_mode)

        if self.seg_len <= 0 or self.hop_len <= 0:
            raise ValueError("segment and hop must be > 0.")
        if n_src < 1 or n_src > 4:
            raise ValueError("ECHI ref positions are pos1..pos4, so n_src must be in [1..4].")
        if self.mixture_mode not in {"manifest", "target_sum"}:
            raise ValueError(
                f"Unsupported mixture_mode='{self.mixture_mode}'. "
                "Expected one of {'manifest', 'target_sum'}."
            )

        # --- load manifests
        self.mix = self._load_manifest(self.json_dir / "mix.json")  # list of [path, len]
        self.targets = []
        for pos in range(1, n_src + 1):
            p = self.json_dir / f"target_pos{pos}.json"
            if not p.is_file():
                # inference-only split possible: no targets
                self.targets = []
                break
            self.targets.append(self._load_manifest(p))

        # --- sanity: alignment by index, same as preprocess_echi.py guarantees
        if self.targets:
            for i in range(len(self.mix)):
                mix_len = self.mix[i][1]
                for k in range(n_src):
                    if self.targets[k][i][1] != mix_len:
                        raise ValueError(
                            f"Manifest length mismatch at i={i}: mix={mix_len}, "
                            f"target_pos{k+1}={self.targets[k][i][1]}"
                        )
        if self.mixture_mode == "target_sum" and not self.targets:
            raise ValueError(
                "mixture_mode='target_sum' requires target_pos*.json manifests, "
                "but no targets were loaded."
            )

        # --- prefix sums for global segment indexing
        self.seg_counts: List[int] = []
        self.cum = [0]
        for _, L in self.mix:
            n = self._num_segments(int(L))
            self.seg_counts.append(n)   #creates a List with the segments counts for each session
            self.cum.append(self.cum[-1] + n) #counts the nummber of total segments for one Dataset

        self.total_segments = self.cum[-1]
        if self.total_segments == 0:
            raise RuntimeError("No segments available (segment length may be larger than recordings).")

    @staticmethod
    def _load_manifest(path: Path) -> List[Tuple[str, int]]:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        return [(str(p), int(n)) for p, n in data]

    def _num_segments(self, L: int) -> int:
        if L < self.seg_len:
            return 1 if self.pad_last else 0
        n_full = 1 + (L - self.seg_len) // self.hop_len
        if not self.pad_last:
            return int(n_full)
        # include tail segment if any remainder not covered
        last_start = (n_full - 1) * self.hop_len
        if last_start + self.seg_len < L:
            return int(n_full + 1)
        return int(n_full)

    def __len__(self) -> int:
        return self.total_segments

    def _locate(self, idx: int) -> Tuple[int, int]:
        if idx < 0:
            idx += self.total_segments
        if idx < 0 or idx >= self.total_segments:
            raise IndexError(idx)
        sess_i = bisect_right(self.cum, idx) - 1
        seg_j = idx - self.cum[sess_i]
        return sess_i, seg_j

    def __getitem__(self, idx: int):
        sess_i, seg_j = self._locate(idx)

        mix_path, mix_len = self.mix[sess_i]
        mix_len = int(mix_len)

        start = seg_j * self.hop_len
        stop = start + self.seg_len

        if stop <= mix_len:
            if self.targets:
                ys = []
                for k in range(self.n_src):
                    y, _ = sf.read(
                        self.targets[k][sess_i][0],
                        start=start,
                        stop=stop,
                        dtype=self.dtype,
                        always_2d=False,
                    )
                    ys.append(y)
            if self.mixture_mode == "target_sum":
                x = np.sum(np.stack(ys, axis=0), axis=0)
            else:
                x, _ = sf.read(
                    mix_path, start=start, stop=stop, dtype=self.dtype, always_2d=False
                )
        else:
            if not self.pad_last:
                raise RuntimeError("Tail segment produced but pad_last=False (indexing bug).")
            pad = stop - mix_len
            if self.targets:
                ys = []
                for k in range(self.n_src):
                    y, _ = sf.read(
                        self.targets[k][sess_i][0],
                        start=start,
                        stop=mix_len,
                        dtype=self.dtype,
                        always_2d=False,
                    )
                    y = np.pad(np.asarray(y), (0, pad), mode="constant")
                    ys.append(y)
            if self.mixture_mode == "target_sum":
                x = np.sum(np.stack(ys, axis=0), axis=0)
            else:
                x, _ = sf.read(
                    mix_path, start=start, stop=mix_len, dtype=self.dtype, always_2d=False
                )
                x = np.pad(np.asarray(x), (0, pad), mode="constant")

        mixture = torch.from_numpy(np.asarray(x)).float()  # [T]
        if self.targets:
            targets = torch.from_numpy(np.stack(ys, axis=0)).float()  # [n_src, T]
        else:
            targets = torch.empty((0, mixture.shape[-1]), dtype=torch.float32)

        utt_id = mix_path if self.return_path else session_key_from_path(mix_path)
        return mixture, targets, utt_id


class ECHIDataModule(object):
    def __init__(
        self,
        train_dir: str,
        valid_dir: str,
        test_dir: str,
        n_src: int = 4,
        sample_rate: int = 16000,
        segment: float = 3.0,
        hop: float | None = None,
        batch_size: int = 8,
        num_workers: int = 4,
        pin_memory: bool = True,
        persistent_workers: bool = True,
        mixture_mode: str = "manifest",
    ) -> None:
        self.train_dir = train_dir
        self.valid_dir = valid_dir
        self.test_dir = test_dir
        self.n_src = n_src
        self.sample_rate = sample_rate
        self.segment = segment
        self.hop = hop
        self.batch_size = batch_size
        self.num_workers = num_workers
        self.pin_memory = pin_memory
        self.persistent_workers = persistent_workers
        self.mixture_mode = mixture_mode

        self.data_train = None
        self.data_val = None
        self.data_test = None

    def setup(self) -> None:
        self.data_train = ECHIDataset(
            json_dir=self.train_dir,
            n_src=self.n_src,
            sample_rate=self.sample_rate,
            segment=self.segment,
            hop=self.hop,
            pad_last=False,      # train: drop tail
            mixture_mode=self.mixture_mode,
        )
        # IMPORTANT: do NOT set segment=None for 36-min files
        self.data_val = ECHIDataset(
            json_dir=self.valid_dir,
            n_src=self.n_src,
            sample_rate=self.sample_rate,
            segment=self.segment,
            hop=self.hop,
            pad_last=False,       # val/test: full coverage if desired
            mixture_mode=self.mixture_mode,
        )
        self.data_test = ECHIDataset(
            json_dir=self.test_dir,
            n_src=self.n_src,
            sample_rate=self.sample_rate,
            segment=self.segment,
            hop=self.hop,
            pad_last=False,
            mixture_mode=self.mixture_mode,
        )

    @property
    def make_loader(self):
        train_loader = DataLoader(
            self.data_train,
            batch_size=self.batch_size,
            shuffle=True,
            num_workers=self.num_workers,
            pin_memory=self.pin_memory,
            persistent_workers=self.persistent_workers,
            drop_last=True,
        )
        val_loader = DataLoader(
            self.data_val,
            batch_size=self.batch_size,
            shuffle=False,
            num_workers=self.num_workers,
            pin_memory=self.pin_memory,
            persistent_workers=self.persistent_workers,
        )
        test_loader = DataLoader(
            self.data_test,
            batch_size=self.batch_size,
            shuffle=False,
            num_workers=self.num_workers,
            pin_memory=self.pin_memory,
            persistent_workers=self.persistent_workers,
        )
        return train_loader, val_loader, test_loader
